<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            Editar Contato ID <?php echo $this->id; ?>        
        </div>
    </div>
    <?php
    // objeto form contato
    $formContato = $this->formContato;
    // preparar elementos do formulário
    $formContato->prepare();
    // configurar url formulário
    $formContato->setAttribute('action', $this->url('contatos', array('action' => 'atualizar')));
    ?>
    
    <?php // renderiza html <form> com atributos configurados no objeto ?>
    <?php echo $this->form()->openTag($formContato) ?>
    <div class="panel-body">
        <div class="form-group">
            <label for="inputNome" class="col-lg-3 col-md-3 control-label">Nome*:</label>
            <div class="col-lg-9 col-md-9">
                <?php 
                // renderiza html input
                echo $this->formInput($formContato->get('nome'));
                
                // renderiza elemento de erro
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($formContato->get('nome'));
                ?>
            </div>
        </div>

        <div class="form-group">
            <label for="inputTelefone" class="col-lg-3 col-md-3 control-label">Telefone*:</label>
            <div class="col-lg-9  col-md-9">
                <?php
                // renderiza html input
                echo $this->formInput($formContato->get('telefone'));
                
                // renderiza elemento de erro
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($formContato->get('telefone'));
                ?>
            </div>
        </div>

        <div class="form-group">
            <label for="inputEmail" class="col-lg-3 col-md-3 control-label">e-mail:</label>
            <div class="col-lg-9  col-md-9">
                <?php
                // renderiza html input
                echo $this->formInput($formContato->get('email'));
                
                // renderiza elemento de erro
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($formContato->get('email'));
                ?>
            </div>
        </div>

        <div class="form-group">
            <label for="inputCaptcha" class="col-lg-3 col-md-3 control-label">Verificação*:</label>
            <div class="col-lg-9  col-md-9" id="captcha">
                <?php
                // renderiza captcha
                echo $this->formCaptcha($formContato->get('captcha'));
                
                // renderiza elemento de erro
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($formContato->get('captcha'));
                ?>
            </div>
        </div>
    </div>
    <div class="panel-footer">
        <?php
        // renderiza html input hidden para id
        echo $this->formHidden($formContato->get('id'));
        // renderiza html input hidden csrf
        echo $this->formElement($formContato->get('security')); 
        ?>

        <button type="submit" class="btn btn-primary">Atualizar Contato</button>
        <a href="<?php echo $this->url('contatos'); ?>" class="btn btn-default">Voltar</a>
    </div>

    <?php // renderiza html </form> ?>
    <?php echo $this->form()->closeTag() ?>
</div>