<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            Novo Contato           
        </div>
    </div>
    <form class="form-horizontal" role="form" method="POST" action="<?php echo $this->url('contatos', array('action' => 'adicionar')); ?>">
        <div class="panel-body">
            <div class="form-group">
                <label for="inputNome" class="col-lg-3 col-md-3 control-label">Nome:</label>
                <div class="col-lg-9 col-md-9">
                    <input type="text" name="nome" class="form-control" id="inputNome" placeholder="Nome Completo">
                </div>
            </div>

            <div class="form-group">
                <label for="inputTelefone" class="col-lg-3 col-md-3 control-label">Telefone:</label>
                <div class="col-lg-9  col-md-9">
                    <input type="text" name="telefone" class="form-control" id="inputTelefone" placeholder="Digite seu telefone">
                </div>
            </div>

            <div class="form-group">
                <label for="inputEmail" class="col-lg-3 col-md-3 control-label">e-mail:</label>
                <div class="col-lg-9  col-md-9">
                    <input type="text" name="email" class="form-control" id="inputEmail" placeholder="Digite seu e-mail (opcional)">
                </div>
            </div>
        </div>
        <div class="panel-footer">
            <button type="submit" class="btn btn-primary">Salvar Contato</button>
            <a href="<?php echo $this->url('contatos'); ?>" class="btn btn-default">Voltar</a>
        </div>
    </form>
</div>